### ISSUE TITLE
Front-end design

### ISSUE THREAD

**Issue by octocatblain** [Chareeef/HAYAT#5]
@KENC0DE @Chareeef kindly add your comments here and I will have a look at them

- [ ]

**Comment by Chareeef** [comment]
It's an awesome work Blain.
I really loved it.
I just would prefer a more related blood donation related pictures in the home page.
And also you need to have 8 blood category options in donations request, though I need you to kindly explain how wd should handle these requests.
Login should also differentiate between log in as a donor or transfusion center. But its design is great.
You're the best.

**Comment by KENC0DE** [comment]
I think that it would be better not to have any image on the landing page. Just good coloring and simple and slick design would do.

**Comment by octocatblain** [comment]
@KENC0DE @Chareeef thank you for your insight. I will check on this in my next update

**Comment by Chareeef** [comment]
@octocatblain Register page is very good. You remind me to add a phone number column to donors and transfusion centers. You only still didn't make separate spaces for donors and TC, in login and Register

**Comment by octocatblain** [comment]
@Chareeef i am working on that and the images. The changes you just merged, I worked on them yesterday and pushed today

**Comment by Chareeef** [comment]
Perfect 👌

**Comment by Chareeef** [comment]
Do you mind if we delete submit donations request section and also stations.
First we just need to display blood  bags situation in different transfusion centers in the home, with location filters.

And as Ken said, avoid gray color. For example I think the top navbar background color could be better in white, as well as forms fields background.

**Comment by Chareeef** [comment]
Pull forms branch @octocatblain
